### ISSUE TITLE
Error: Command failed: which...

### ISSUE THREAD

**Issue by eyesno** [splash-cli/splash-cli#37] opened 2018-11-24 02:14 UTC
#### Basic informations
- **Splash CLI** version: 3.3.0
- Node version: v8.10.0
- Your OS: Ubuntu 18.04.1

#### Before you go
- [?] I've read the [FAQ](https://github.com/splash-cli/splash-cli/blob/master/FAQ.md) section.

^ 404 Error

- [X] I've the latest version of **Splash CLI installed**
- [X ] I've searched other issues like mine but I haven't found a solution.

# The ISSUE
✔ Connected!
✔ Something is happening...
Error: Command failed: which -a gsettings; which -a setroot; which -a pcmanfm; which -a feh; which -a nitrogen; which -a xfconf-query; which -a gconftool-2; which -a dcop; which -a dconf; which -a qdbus

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)

**To Reproduce**
1. Run `splash --today`

**Expected behavior**
I expected it to download and replace my wallpaper. :/

**Console Output**
See above. 
```
```

**Comment by Rawnly** [comment] 2018-11-24 02:20
The “—today” flag does not exist. It is —day..

However I don’t think that this is the cause o f the problem. Tomorrow morning I’ll investigate 🤔

I’m sorry to all Linux users but I don’t have a Linux machine to test Splash Cli on.

**Comment by eyesno** [comment] 2018-11-26 00:44
I get the following (screenshot attached).

✔ Connected!
🌍 Magic stuffevents.js:183
throw er; // Unhandled 'error' event
^

Error: EACCES: permission denied, open '/home/darrylwright/Pictures/splash_photos/ATsEkysmm0Y.jpg'

**Comment by Rawnly** [comment] 2018-11-26 00:47
Have you tried editing permissions of the following path?

<code>home/darrylwright/Pictures/splash_photos</code>

**Comment by eyesno** [comment] 2018-11-26 03:51
That folder doesn't exist. The pictures are getting downloaded to my home folder.

**Comment by Rawnly** [comment] 2018-11-26 17:01
Try by creating it via `mkdir -p ~/Pictures/splash_photos` or may be changing the default dir in `splash-cli` to a custom path.

---

To change the dir of `splash-cli` just do the following:

```sh
  splash settings
  # ... Then is the 2nd question that is presented.
```

**Comment by eyesno** [comment] 2018-11-26 23:39
I tried creating ~/Pictures/splash_photos manually and it had no effect. When I tried to run splash settings I saw the following screen (attached). I am afraid I don't know what any of these means so it wasn't clear where to set the folder. I couldn't get past the first question.

**Comment by Rawnly** [comment] 2018-11-26 23:41
Can’t see the attached screen 😅

**Comment by Rawnly** [comment] 2018-11-29 00:45
Are you sure you had installed `splash-cli` correctly? This doesn't seems to be `splash-cli`.

#### [NPM](http://npmjs.org)
- **Uninstall**: `npm remove -g splash-cli` 
- **Installation**:  `npm i -g splash-cli`

#### [YARN](https://yarnpkg.com)
- **Uninstall**: `yarn global remove  splash-cli` 
- **Installation**:  `yarn global add splash-cli`

**Comment by eyesno** [comment] 2018-11-29 16:02
Ok -- so I uninstalled and reinstalled and this time the settings worked perfectly. There is a default folder setup for the splash images. But I still seem to get the same crash. The download part seems to function perfectly but whatever that last step is results in this:

Error: Command failed: which -a gsettings; which -a setroot; which -a pcmanfm; which -a feh; which -a nitrogen; which -a xfconf-query; which -a gconftool-2; which -a dcop; which -a dconf; which -a qdbus

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by Rawnly** [comment] 2019-01-03 02:09
Sorry for inactivity, please keep watching #34

**Comment by eyesno** [comment] 2019-01-21 15:39
Sorry guys -- I actually wound up buying a Macbook Pro and switching back
to MacOS! :)

**Comment by Rawnly** [comment] 2019-01-21 15:40
So I can close this issue?

**Comment by eyesno** [comment] 2019-01-21 17:46
It's up to you, of course, but if nobody else has reported it and you're
unable to reproduce it, I suppose it would make sense.

Darryl

**Comment by Rawnly** [comment] 2019-01-22 01:04
Perfect 👌🏻 I just wanted your confirm before closing it✌️

**Closed by Rawnly** 2019-01-22 01:04 UTC
Labels: Help Wanted, Platform: Linux 🐧, node v8.x
