### ISSUE TITLE
[HTTPError]: Response code 401 (Unauthorized)

### ISSUE THREAD

**Issue by jondewitt** [splash-cli/splash-cli#53] opened 2019-09-17 22:44 UTC
#### Basic informations
- **Splash CLI** version: `3.4.0`
- Node version: `6.11.3`
- Yarn version: `1.17.3`
- Your OS: **MacOS 10.13.6**

#### Before you go
- [x] I've read the [FAQ](https://github.com/splash-cli/splash-cli/blob/master/FAQ.md) section.
- [x] I've the latest version of **Splash CLI installed**
- [x] I've searched other issues like mine but I haven't found a solution.

# The ISSUE
HTTP 401 Unauthorization issue with Splash API happens with any command. NPM or Yarn use seems irrelevant. Started happening recently so I updated everything involved but still I have the error.

**To Reproduce**
1. Run any `splash` command that fetches a new background, I usually do `-c` or `-f`

**Expected behavior**
Background updates after a moment

**Console Output**

```
GotError [HTTPError]: Response code 401 (Unauthorized)
    at /Users/my.user/.config/yarn/global/node_modules/got/index.js:386:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'HTTPError',
  host: 'api.unsplash.com',
  hostname: 'api.unsplash.com',
  method: 'GET',
  path: '/photos/random?client_id=a70f2ffae3634a7bbb5b3f94998e49ccb2e85922fa3215ccb61e022cf57ca72c&count=1&featured=false',
  protocol: 'https:',
  url: 'https://api.unsplash.com/photos/random?client_id=a70f2ffae3634a7bbb5b3f94998e49ccb2e85922fa3215ccb61e022cf57ca72c&count=1&featured=false',
  statusCode: 401,
  statusMessage: 'Unauthorized',
  headers: {
    server: 'Cowboy',
    'content-type': 'application/json',
    'access-control-allow-origin': '*',
    'access-control-request-method': '*',
    'access-control-allow-headers': '*',
    'access-control-expose-headers': 'Link,X-Total,X-Per-Page,X-RateLimit-Limit,X-RateLimit-Remaining',
    'cache-control': 'no-cache',
    'x-request-id': 'd53c3d03-878d-4f01-9436-baa32b639483',
    'x-runtime': '0.012741',
    'strict-transport-security': 'max-age=31536000; includeSubDomains',
    via: '1.1 vegur, 1.1 varnish, 1.1 varnish',
    'accept-ranges': 'bytes, bytes, bytes, bytes',
    'content-length': '55',
    date: 'Tue, 17 Sep 2019 22:40:08 GMT',
    connection: 'close',
    'x-served-by': 'cache-iad2126-IAD, cache-lax8632-LAX',
    'x-cache': 'MISS, MISS',
    'x-cache-hits': '0, 0',
    'x-timer': 'S1568760008.131680,VS0,VE77',
    vary: 'Origin, Authorization'
  }
}
✖ Unable to connect.
```

**Comment by lalitaalaalitah** [comment] 2019-09-20 13:19
Can confirm. Got same. I thought that it's my firewall. But, unblocked access yields same result.

**Comment by Rawnly** [comment] 2019-09-20 13:29
Hi guys, it’s not your problem, I’ve requested a refresh of api keys since I’ve noticed an unusual usage on the Unsplash dashboard (5000 in 1 hour...), give me a few days I’ll release a new version, in the meantime you can go over api.unsplash.com get your own api key and set it via cli settings

**Comment by Rawnly** [comment] 2019-09-20 13:35
You can follow the development in the [`new-authentication`](https://github.com/splash-cli/splash-cli/tree/feature/new-authentication) branch

**Comment by Rawnly** [comment] 2019-09-22 10:10
Can you try with the new beta version? 

```sh
	$ npm i -g splash-cli@3.4.2 beta
```

**Comment by lalitaalaalitah** [comment] 2019-09-22 12:48
OK. Tested. Unauthorized still.
Here is the output:
`✖ GotError [HTTPError]: Response code 401 (Unauthorized)
    at /usr/local/lib/node_modules/splash-cli/node_modules/got/index.js:386:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'HTTPError',
  host: 'api.unsplash.com',
  hostname: 'api.unsplash.com',
  method: 'GET',
  path: '/photos/random?client_id=a70f2ffae3634a7bbb5b3f94998e49ccb2e85922fa3215ccb61e022cf57ca72c&count=1&featured=false',
  protocol: 'https:',
  url: 'https://api.unsplash.com/photos/random?client_id=a70f2ffae3634a7bbb5b3f94998e49ccb2e85922fa3215ccb61e022cf57ca72c&count=1&featured=false',
  statusCode: 401,
  statusMessage: 'Unauthorized',
  headers: {
    server: 'Cowboy',
    'content-type': 'application/json',
    'access-control-allow-origin': '*',
    'access-control-request-method': '*',
    'access-control-allow-headers': '*',
    'access-control-expose-headers': 'Link,X-Total,X-Per-Page,X-RateLimit-Limit,X-RateLimit-Remaining',
    'cache-control': 'no-cache',
    'x-request-id': '9ae649c4-cbdf-4229-a40e-8416f05973d0',
    'x-runtime': '0.012763',
    'strict-transport-security': 'max-age=31536000; includeSubDomains',
    via: '1.1 vegur, 1.1 varnish, 1.1 varnish',
    'accept-ranges': 'bytes, bytes, bytes, bytes',
    'content-length': '55',
    date: 'Sun, 22 Sep 2019 12:47:31 GMT',
    connection: 'close',
    'x-served-by': 'cache-iad2145-IAD, cache-bom18222-BOM',
    'x-cache': 'MISS, MISS',
    'x-cache-hits': '0, 0',
    'x-timer': 'S1569156451.209851,VS0,VE256',
    vary: 'Origin, Authorization'
  }
}
✖ Unable to connect.`

**Comment by Rawnly** [comment] 2019-09-22 13:00
>   path: '/photos/random?client_id=**a70f2ffae3634a7bbb5b3f94998e49ccb2e85922fa3215ccb61e022cf57ca72c**&count=1&featured=false',

This is the old key... Maybe you should clean your installation

**Comment by lalitaalaalitah** [comment] 2019-09-23 09:15
Ok.
I uninstalled with npm, then confirmed that no file exists in `~/.config/configstore/` and then installed splash-cli. Still getting the same key in error log.
What I missed?
Please, suggest a way to properly uninstall.

**Comment by Rawnly** [comment] 2019-09-23 22:47
can you run `splash --version` ?

**Comment by TotomInc** [comment] 2019-09-24 07:30
I've also uninstalled and installed the `3.4.2` beta but it still doesn't works. It keeps trying to access the API with the old `client_id`.

```js
Splash Error:

✖ { HTTPError: Response code 401 (Unauthorized)
    at stream.catch.then.data (/Users/thca/.nvm/versions/node/v10.16.3/lib/node_modules/splash-cli/node_modules/got/index.js:386:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'HTTPError',
  host: 'api.unsplash.com',
  hostname: 'api.unsplash.com',
  method: 'GET',
  path:
   '/photos/random?client_id=a70f2ffae3634a7bbb5b3f94998e49ccb2e85922fa3215ccb61e022cf57ca72c&count=1&collections=wallpapers&featured=false',
  protocol: 'https:',
  url:
   'https://api.unsplash.com/photos/random?client_id=a70f2ffae3634a7bbb5b3f94998e49ccb2e85922fa3215ccb61e022cf57ca72c&count=1&collections=wallpapers&featured=false',
  statusCode: 401,
  statusMessage: 'Unauthorized',
  headers:
   { server: 'Cowboy',
     'content-type': 'application/json',
     'access-control-allow-origin': '*',
     'access-control-request-method': '*',
     'access-control-allow-headers': '*',
     'access-control-expose-headers':
      'Link,X-Total,X-Per-Page,X-RateLimit-Limit,X-RateLimit-Remaining',
     'cache-control': 'no-cache',
     'x-request-id': '90f26270-ee3b-45b6-a96a-331278d0ec76',
     'x-runtime': '0.012403',
     'strict-transport-security': 'max-age=31536000; includeSubDomains',
     via: '1.1 vegur, 1.1 varnish, 1.1 varnish',
     'accept-ranges': 'bytes, bytes, bytes, bytes',
     'content-length': '55',
     date: 'Tue, 24 Sep 2019 07:29:13 GMT',
     connection: 'close',
     'x-served-by': 'cache-iad2148-IAD, cache-cdg20764-CDG',
     'x-cache': 'MISS, MISS',
     'x-cache-hits': '0, 0',
     'x-timer': 'S1569310154.553366,VS0,VE98',
     vary: 'Origin, Authorization' } }
✖ Unable to connect.
```

**Comment by Rawnly** [comment] 2019-09-26 14:35
Ok guys, thank you for reporting. Unfortunately I'm the only person that's maintaining this project. Have patience as soon as I can, I'll try to fix.

If you'd like to contribute please drop me a message [here](mailto:fedevitale99@gmail.com?subject=splash%20cli)

**Comment by TotomInc** [comment] 2019-09-26 17:04
Well, as you see in the error response, it's a 401 Unauthorized, which surely means the client_id used is not valid anymore.

You can regenerate a new one and pass it on a new version of splash-cli or even add a feature that would let the user use his own token from unsplash.

We all understand that maintening open source projects takes time when you have a full time work, no pressure. 😀

**Comment by Rawnly** [comment] 2019-09-26 17:08
Yeah I’ve already regenerated the keys and pushed the 3.4.2 beta with new keys but i can’t understand why it keeps old keys... in thinking of refactoring the entire authentication method

**Comment by Rawnly** [comment] 2019-10-02 08:16
Please try deleting `/Users/<your_username>/Library/Preferences/splash-cli-nodejs/config.json`

**Comment by delfu** [comment] 2019-10-13 03:33
@Rawnly i got 3.4.2 beta. In the code of the package, it's still using the old key (inside src/extra/config.js)

**Comment by delfu** [comment] 2019-10-13 03:41
@Rawnly i can confirm changing the appId/secret fixes the issue. I did it using my own keys

**Comment by Rawnly** [comment] 2019-10-13 17:25
> @Rawnly i got 3.4.2 beta. In the code of the package, it's still using the old key (inside src/extra/config.js)

Sorry i've pushed the wrong branch 😅, i'm fixing it right now

**Comment by Rawnly** [comment] 2019-10-13 17:39
Let me know if this latest release has fixed the issue

**Comment by Rawnly** [comment] 2019-10-14 20:33
Hi guys if no one will answer i'll mark this issue as closed. Please update to version `3.4.4`

**Comment by TotomInc** [comment] 2019-10-15 07:49
Yes it works fine now after upgrading to `3.4.4`.

You can close the issue.

**Comment by Rawnly** [comment] 2019-10-15 07:50
Awesome, thanks for reporting ✌️

**Closed by Rawnly** 2019-10-15 07:50 UTC
Labels: :construction_worker_man: Work In Progress, Platform: All, Testing, enhancement
